# Generated by Django 3.2 on 2022-01-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220107_0340'),
        ('community', '0005_auto_20220111_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='username',
        ),
        migrations.AddField(
            model_name='comments',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profiles.userprofile'),
        ),
    ]
