# Generated by Django 3.2 on 2022-01-14 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20220113_0610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
