# Generated by Django 3.2 on 2021-12-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211223_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
