# Generated by Django 3.2 on 2022-01-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_price',
        ),
    ]
